name: 🐛 Bug Report
description: Report a bug or unexpected behavior in ThreatSimGPT
title: "[BUG] "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: checkboxes
    id: existing-issue
    attributes:
      label: Existing Issue Check
      description: Please confirm you've checked for existing issues
      options:
        - label: I have searched the existing issues and this is a new bug
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. With configuration '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - CLI
        - API
        - LLM Integration
        - Template System
        - RAG System
        - Safety Framework
        - Configuration
        - Documentation
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: ThreatSimGPT Version
      description: Output of `threatsimgpt --version`
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: Output of `python --version`
      placeholder: "3.11.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux (Ubuntu)
        - Linux (Other)
        - Windows
        - Docker
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please copy and paste any relevant log output
      render: shell

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Relevant parts of your config.yaml (remove sensitive data)
      render: yaml

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
